name: Build e Deploy

on:
  release:
    types: [published]

jobs:
  build:
    name: Gerar Binario e Instalador
    runs-on: windows-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js v12
        uses: actions/setup-node@v3
        with:
          node-version: "12"
          cache: "npm"

      - name: Instalar dependências
        run: npm install

      - name: Compilar o executável
        run: npm run build

      - name: Instalar NSIS
        run: |
          choco install nsis -y
          echo "C:\Program Files (x86)\NSIS" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Extrair versão da tag
        id: get_version
        run: |
          $version = "${{ github.ref_name }}"
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT
        shell: powershell

      - name: Compilar o instalador com versão
        run: |
          makensis installer.nsi
          $version = "${{ steps.get_version.outputs.VERSION }}"
          Rename-Item "NodeBackupInstaller.exe" "NodeBackupInstaller-$version.exe"
        shell: powershell

      - name: Fazer upload do instalador para a release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./NodeBackupInstaller-${{ steps.get_version.outputs.VERSION }}.exe
          asset_name: NodeBackupInstaller-${{ steps.get_version.outputs.VERSION }}.exe
          asset_content_type: application/octet-stream
